parameters:
    cim.plupload.form.type.class: CIM\PluploadBundle\Form\PluploadType
    cim.plupload.form.type.injection.class: CIM\PluploadBundle\Listener\PluploadTypeListener
    cim.plupload.twig.filesize.class: CIM\PluploadBundle\Twig\FileSizeExtension

services:
    cim.plupload.form.type:
        class: %cim.plupload.form.type.class%
        arguments: [@service_container, @cim.plupload.form.type.injection]
        tags:
            -
                name: form.type
                alias: plupload

    cim.plupload.form.type.injection:
        class: %cim.plupload.form.type.injection.class%
        arguments:	[@templating.engine.twig]
        tags:
            -
                name: kernel.event_listener
                event: kernel.response
                method: onKernelResponse

    cim.plupload.twig.filesize:
        class: %cim.plupload.twig.filesize.class%
        tags:
            - { name: twig.extension }